"""Seed rows for the Sourcing Intel sheet.

The sheet is the source of truth once seeded — edit rows there, not here. This
file exists so the research universe and its inspection guides can be restored
or re-seeded, and so what went in is on record.

Every row is a research target, not a verdict: nothing here says an item is a
good buy. Market data pulled for the eBay/Poshmark queries decides the score.
Typical Cost Low/High are rough thrift-shelf estimates (sourcing intelligence,
shown on the site as estimates), not marketplace data.

Fields: t=search term, cat=category, sub=subcategory, eb=eBay query,
pm=Poshmark query, ship=shipping class, test/fake/ret=testing, counterfeit and
return risk, frag=fragility, know=knowledge level, req=condition requirement,
cost=(low, high), loc=sourcing locations, chk=inspection checklist,
see=recognition clues, plat=platform notes.
"""
import json, re, sys

L, M, H = 'Low', 'Medium', 'High'
EASY, MOD, DIFF = 'Easy', 'Moderate', 'Difficult'
BEG, MODK, SPEC = 'Beginner', 'Moderate', 'Specialist'
UNTESTED, RECOMMENDED, MUST, AUTH = 'Works untested', 'Testing recommended', 'Must test', 'Authentication concern'
ALL = 'Bins, Thrift store, Yard sale, Estate sale, Marketplace, Flea market'

SHIP_DIFFICULTY = {'small': EASY, 'medium': EASY, 'large': MOD, 'bulky': DIFF, 'local': DIFF}

ROWS = [
  # ------------------------------------------------------------------ Fashion (existing Market Trends terms)
  dict(t='Carhartt jacket', cat='Fashion', sub='Outerwear', brand='Carhartt', eb='carhartt jacket -hat -beanie -kids', pm='Carhartt jacket',
       ship='medium', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(8, 25), loc='Thrift store, Bins, Yard sale, Estate sale',
       chk=['Check cuffs, collar and pocket edges for fraying', 'Zipper runs the full length', 'Look for paint, oil or bleach spots', 'Blanket or quilted lining intact'],
       see=['Detroit, Active and Chore coat styles sell best', 'Brown duck canvas and blanket lining', 'Union-made or USA tags point to older, stronger sellers', 'Distressed vintage wear is fine — buyers want it']),
  dict(t='Patagonia fleece', cat='Fashion', sub='Outerwear', brand='Patagonia', eb='patagonia fleece jacket -kids -baby', pm='Patagonia fleece',
       ship='medium', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(6, 20), loc='Thrift store, Bins, Estate sale',
       chk=['Pilling on sleeves and sides', 'Snaps and zippers work', 'No pet-hair matting or odor'],
       see=['Synchilla snap-T and Better Sweater models', 'Retro-X and Retro Pile deep-pile fleece', 'Older "made in USA" tags carry a premium']),
  dict(t='Patagonia jacket', cat='Fashion', sub='Outerwear', brand='Patagonia', eb='patagonia jacket -fleece -kids -baby', pm='Patagonia jacket',
       ship='medium', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(8, 25), loc='Thrift store, Bins, Estate sale',
       chk=['Seam tape inside shell jackets is not peeling', 'Down baffles are not flat or leaking', 'Zippers and hood cords work'],
       see=['Nano Puff, Down Sweater, Torrentshell', 'Patagonia fitz roy mountain logo tag', 'Technical shells sell above casual jackets']),
  dict(t='The North Face jacket', cat='Fashion', sub='Outerwear', brand='The North Face', eb='the north face jacket -kids -baby -patch', pm='The North Face jacket',
       ship='medium', test=L, fake=M, ret=L, frag=L, know=MODK, req=AUTH, cost=(8, 25), loc='Thrift store, Bins, Yard sale',
       chk=['Down puffers: no flat spots or feather leaks', 'Check inner tag stitching and hologram on newer pieces', 'Zippers are YKK and branded'],
       see=['Nuptse 700 and Denali fleece are the strongest styles', 'Summit Series is the premium line', 'Fake Nuptses have uneven baffles and sloppy logo embroidery']),
  dict(t='The North Face fleece vest', cat='Fashion', sub='Outerwear', brand='The North Face', eb='the north face fleece vest -kids', pm='The North Face fleece vest',
       ship='small', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(4, 12), loc='Thrift store, Bins',
       chk=['Pilling on the chest', 'Zipper pull present'], see=['Denali-style vests with nylon overlays sell best']),
  dict(t="Levi's denim jacket", cat='Fashion', sub='Outerwear', brand="Levi's", eb="levis denim trucker jacket -kids", pm="Levi's denim jacket",
       ship='medium', test=L, fake=L, ret=L, frag=L, know=MODK, req=UNTESTED, cost=(6, 20), loc='Thrift store, Bins, Estate sale, Flea market',
       chk=['Buttons all present and stamped', 'Collar and cuffs not shredded', 'Measure pit-to-pit for sizing'],
       see=['Type III trucker with pleated front', 'Big E red tab = pre-1971 and valuable', 'Sherpa-lined versions sell higher']),
  dict(t='Nike windbreaker', cat='Fashion', sub='Outerwear', brand='Nike', eb='vintage nike windbreaker jacket', pm='Nike windbreaker',
       ship='small', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(4, 15), loc='Thrift store, Bins, Yard sale',
       chk=['No cracked lining or sticky coating', 'Zipper and cuffs intact'], see=['90s colorblock styles', 'Silver or white tag vintage Nike']),
  dict(t='Adidas track jacket', cat='Fashion', sub='Outerwear', brand='Adidas', eb='vintage adidas track jacket', pm='Adidas track jacket',
       ship='small', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(4, 15), loc='Thrift store, Bins',
       chk=['Stripes not peeling', 'Zipper works'], see=['Trefoil logo, made in West Germany or Japan tags', 'Firebird and Beckenbauer styles']),
  dict(t='Columbia fleece jacket', cat='Fashion', sub='Outerwear', brand='Columbia', eb='columbia fleece jacket -kids', pm='Columbia fleece jacket',
       ship='small', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(3, 10), loc='Thrift store, Bins',
       chk=['Pilling', 'Zipper works'], see=['Common and low-priced — only worth it cheap or in vintage colorways']),
  dict(t='Champion hoodie', cat='Fashion', sub='Shirts', brand='Champion', eb='champion reverse weave hoodie', pm='Champion hoodie',
       ship='small', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(3, 12), loc='Thrift store, Bins',
       chk=['Cuffs and hem not stretched out', 'No stains on the front'], see=['Reverse Weave with side panels', 'Vintage college prints sell best']),
  dict(t='Vintage band t-shirt', cat='Fashion', sub='Vintage clothing', eb='vintage band t shirt single stitch', pm='Vintage band t-shirt',
       ship='small', test=L, fake=H, ret=M, frag=L, know=SPEC, req=AUTH, cost=(2, 15), loc='Thrift store, Bins, Estate sale, Flea market',
       chk=['Single-stitch hem on sleeves and bottom', 'Tag and print age match (no modern tags on "vintage")', 'Check for holes and pit stains'],
       see=['Brockum, Giant, Winterland, Tultex, Screen Stars tags', 'Tour dates printed on the back', 'Modern reprints use tearaway tags and soft-hand prints']),
  dict(t='Vintage flannel shirt', cat='Fashion', sub='Vintage clothing', eb='vintage flannel shirt', pm='Vintage flannel shirt',
       ship='small', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(3, 10), loc='Thrift store, Bins, Estate sale',
       chk=['Elbows not worn through', 'Buttons all present'], see=['Pendleton wool, Woolrich, St. Johns Bay heavy cotton', 'Made in USA tags']),
  dict(t='Ralph Lauren polo', cat='Fashion', sub='Shirts', brand='Ralph Lauren', eb='polo ralph lauren shirt -kids -boys', pm='Ralph Lauren polo',
       ship='small', test=L, fake=M, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(3, 10), loc='Thrift store, Bins, Yard sale',
       chk=['Collar not curled', 'No underarm stains'], see=['Big Pony and vintage "Polo Sport" pieces sell higher', 'Plain small-pony polos are common — buy only cheap']),
  dict(t='Carhartt overalls', cat='Fashion', sub='Pants', brand='Carhartt', eb='carhartt bib overalls -kids', pm='Carhartt overalls',
       ship='medium', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(8, 25), loc='Thrift store, Yard sale, Estate sale',
       chk=['Buckles and straps intact', 'Knee wear is fine; torn crotch is not'], see=['Double-knee duck bibs', 'Quilt-lined insulated bibs sell in fall/winter']),
  dict(t="Levi's 501 jeans", cat='Fashion', sub='Pants', brand="Levi's", eb='levis 501 jeans -kids', pm="Levi's 501 jeans",
       ship='small', test=L, fake=L, ret=M, frag=L, know=MODK, req=UNTESTED, cost=(4, 15), loc='Thrift store, Bins, Flea market',
       chk=['Measure the actual waist and inseam — tags lie on old denim', 'Crotch blowouts', 'Button fly all present'],
       see=['Made in USA tag and "555" button stamp', 'Big E red tab', 'Orange tab and 505/517 also sell']),
  dict(t='Wrangler jeans', cat='Fashion', sub='Pants', brand='Wrangler', eb='vintage wrangler jeans', pm='Wrangler jeans',
       ship='small', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(3, 10), loc='Thrift store, Bins',
       chk=['Measure waist and inseam'], see=['13MWZ cowboy cut', 'Made in USA']),
  dict(t='Dickies pants', cat='Fashion', sub='Pants', brand='Dickies', eb='dickies 874 work pants', pm='Dickies pants',
       ship='small', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(3, 8), loc='Thrift store, Bins',
       chk=['Hems not frayed'], see=['874 original fit', 'Double-knee work pants']),
  dict(t='Lululemon leggings', cat='Fashion', sub='Pants', brand='Lululemon', eb='lululemon align leggings', pm='Lululemon leggings',
       ship='small', test=L, fake=M, ret=M, frag=L, know=MODK, req=AUTH, cost=(4, 15), loc='Thrift store, Bins',
       chk=['Pilling in the inner thigh', 'Size dot/tag inside the waistband', 'Hold up to light for sheerness'],
       see=['Align and Wunder Under are the best sellers', 'Real pairs have a size tag hidden in the waistband pocket']),
  dict(t='Calvin Klein jeans', cat='Fashion', sub='Pants', brand='Calvin Klein', eb='calvin klein jeans', pm='Calvin Klein jeans',
       ship='small', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(3, 8), loc='Thrift store, Bins',
       chk=['Measure waist and inseam'], see=['Vintage 90s high-rise CK sells; modern pairs are common']),
  dict(t='Nike Jordan sneakers', cat='Fashion', sub='Shoes', brand='Nike', eb='air jordan retro sneakers -kids -toddler -gs -td', pm='Nike Jordan sneakers',
       ship='medium', test=L, fake=H, ret=M, frag=L, know=SPEC, req=AUTH, cost=(10, 40), loc='Thrift store, Marketplace, Yard sale',
       chk=['Size tag inside matches both shoes', 'Stitching count and spacing even', 'Sole separation and heel drag', 'Smell test — fakes smell of glue'],
       see=['Retro 1, 3, 4, 11 are the strongest', 'Check the production date on the size tag', 'Replicas have wrong Wings logo depth and toe box shape']),
  dict(t='New Balance sneakers', cat='Fashion', sub='Shoes', brand='New Balance', eb='new balance 990 sneakers -kids', pm='New Balance sneakers',
       ship='medium', test=L, fake=L, ret=L, frag=L, know=MODK, req=UNTESTED, cost=(6, 20), loc='Thrift store, Bins, Yard sale',
       chk=['Midsole not crumbling on older pairs', 'Insoles present'], see=['990-series made in USA', '550 and 2002R are hot lifestyle models']),
  dict(t='Vans Old Skool', cat='Fashion', sub='Shoes', brand='Vans', eb='vans old skool shoes -kids -toddler', pm='Vans Old Skool',
       ship='medium', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(4, 12), loc='Thrift store, Bins',
       chk=['Sole wear on the heel', 'Suede not torn'], see=['Collabs and checkerboard sell above plain black']),
  dict(t='Doc Martens boots', cat='Fashion', sub='Shoes', brand='Dr. Martens', eb='dr martens boots 1460 -kids', pm='Doc Martens boots',
       ship='medium', test=L, fake=L, ret=L, frag=L, know=MODK, req=UNTESTED, cost=(8, 30), loc='Thrift store, Estate sale, Flea market',
       chk=['Air-cushioned sole not split', 'Leather cracks at the flex point'], see=['1460 8-eye and Jadon platform', '"Made in England" pairs are worth more']),
  dict(t='Timberland boots', cat='Fashion', sub='Shoes', brand='Timberland', eb='timberland 6 inch premium boots -kids -toddler', pm='Timberland boots',
       ship='medium', test=L, fake=M, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(8, 25), loc='Thrift store, Bins, Yard sale',
       chk=['Nubuck stains and scuffs', 'Collar padding intact', 'Sole wear'], see=['Classic wheat 6-inch premium', 'Fakes have flimsy collars and thin laces']),
  dict(t='Ugg boots', cat='Fashion', sub='Shoes', brand='UGG', eb='ugg classic boots women -kids', pm='Ugg boots',
       ship='medium', test=L, fake=H, ret=M, frag=L, know=MODK, req=AUTH, cost=(6, 20), loc='Thrift store, Bins',
       chk=['Sheepskin inside not matted flat', 'Heel not collapsed', 'Look for the security label inside the left boot'],
       see=['Classic Short, Mini and Tasman slippers', 'Fakes feel synthetic inside and have thin soles']),
  dict(t='Vans shoes', cat='Fashion', sub='Shoes', brand='Vans', eb='vans shoes -kids -toddler', pm='Vans shoes',
       ship='medium', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(4, 12), loc='Thrift store, Bins',
       chk=['Sole wear'], see=['Slip-on checkerboard and Sk8-Hi']),
  dict(t='Coach bag', cat='Fashion', sub='Bags', brand='Coach', eb='coach leather handbag -wallet -wristlet', pm='Coach bag',
       ship='medium', test=L, fake=H, ret=M, frag=L, know=MODK, req=AUTH, cost=(5, 25), loc='Thrift store, Estate sale, Yard sale, Flea market',
       chk=['Creed patch inside with a serial number', 'Stitching straight and even', 'Hardware is heavy and branded', 'Corners and handles not worn through'],
       see=['Vintage glove-tanned leather bags (made in USA/NYC) sell best', 'Signature-C canvas is common — authenticate carefully', 'Fakes have creed text that runs off the patch']),
  dict(t='Ray-Ban sunglasses', cat='Fashion', sub='Accessories', brand='Ray-Ban', eb='ray-ban sunglasses -replacement -lenses', pm='Ray-Ban sunglasses',
       ship='small', test=L, fake=H, ret=M, frag=M, know=MODK, req=AUTH, cost=(3, 15), loc='Thrift store, Bins, Yard sale',
       chk=['Model number and "Made in Italy" on the inner arm', 'RB etched on the left lens', 'Hinges tight, no cracks'],
       see=['Wayfarer RB2140, Clubmaster RB3016, Aviator RB3025', 'Fakes lack the tiny "RB" etching']),
  dict(t='Burberry scarf', cat='Fashion', sub='Designer', brand='Burberry', eb='burberry cashmere scarf', pm='Burberry scarf',
       ship='small', test=L, fake=H, ret=M, frag=L, know=SPEC, req=AUTH, cost=(3, 20), loc='Thrift store, Estate sale',
       chk=['100% cashmere tag, made in Scotland', 'Check pattern lines up at the edges', 'Fringe is even'],
       see=['Nova check scarves', 'Fakes feel scratchy and the check pattern is off-scale']),
  dict(t='Stanley tumbler', cat='Home', sub='Kitchenware', brand='Stanley', eb='stanley quencher tumbler 40 oz', pm='Stanley tumbler',
       ship='medium', test=L, fake=M, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(3, 15), loc='Thrift store, Yard sale, Marketplace',
       chk=['No dents in the insulated wall', 'Lid and straw present', 'Logo not peeling'], see=['Quencher H2.0 limited colors sell highest', 'Classic green vacuum bottles too']),
  dict(t='Yeti tumbler', cat='Home', sub='Kitchenware', brand='YETI', eb='yeti rambler tumbler', pm='Yeti tumbler',
       ship='small', test=L, fake=M, ret=L, frag=L, know=BEG, req=UNTESTED, cost=(3, 12), loc='Thrift store, Yard sale',
       chk=['Dents break the vacuum seal', 'Lid included'], see=['Rambler 20/30 oz and discontinued colors']),

  # ------------------------------------------------------------------ Electronics
  dict(t='Sony Handycam Digital8 camcorder', cat='Electronics', sub='Camcorders', brand='Sony', model='DCR-TRV series',
       eb='sony digital8 handycam camcorder -tape -tapes -battery -charger -case', ship='medium', test=H, fake=L, ret=M, frag=M, know=MODK, req=MUST,
       cost=(5, 25), loc='Thrift store, Estate sale, Yard sale, Bins',
       chk=['Powers on (bring a battery or ask to plug it in)', 'Tape door opens and a tape loads', 'Lens has no haze or fungus', 'LCD flip-out screen and viewfinder work', 'Battery compartment free of corrosion', 'Look for charger, battery and AV cables'],
       see=['"Digital8" logo on the tape door', 'Model numbers DCR-TRV and DCR-TRV...E', 'Large InfoLithium battery on the back', 'NightShot switch']),
  dict(t='MiniDV camcorder', cat='Electronics', sub='Camcorders', model='Canon ZR / Panasonic PV / Sony DCR-HC',
       eb='minidv camcorder -tape -tapes -battery -charger -case -lot', ship='medium', test=H, fake=L, ret=M, frag=M, know=MODK, req=MUST,
       cost=(5, 25), loc='Thrift store, Estate sale, Yard sale',
       chk=['Powers on and ejects a tape', 'Plays back without a "clean heads" error', 'LCD works', 'Battery and charger included'],
       see=['"MiniDV" logo', 'Canon ZR/Vixia HV, Sony DCR-HC and Panasonic PV-GS models', 'FireWire (DV) port']),
  dict(t='Canon PowerShot ELPH digital camera', cat='Electronics', sub='Cameras', brand='Canon', model='PowerShot ELPH / SD series',
       eb='canon powershot elph digital camera -battery -charger -case', ship='small', test=M, fake=L, ret=M, frag=M, know=BEG, req=RECOMMENDED,
       cost=(4, 20), loc='Thrift store, Bins, Yard sale, Estate sale',
       chk=['Lens extends and retracts smoothly', 'Screen has no dead pixels or cracks', 'Battery door latch intact', 'Charger or battery included'],
       see=['Canon PowerShot ELPH and SD series', 'Y2K compact cameras are trending with younger buyers', '"Lens error" usually means it needs parts pricing']),
  dict(t='35mm point and shoot film camera', cat='Electronics', sub='Cameras', model='Olympus Stylus / Yashica / Canon Sure Shot',
       eb='35mm point and shoot film camera -lens -lot -parts', ship='small', test=H, fake=L, ret=M, frag=M, know=MODK, req=MUST,
       cost=(3, 20), loc='Thrift store, Estate sale, Yard sale, Flea market',
       chk=['Battery compartment clean', 'Lens cover slides and lens extends', 'Flash fires', 'Shutter clicks when advanced', 'Film door seal not sticky'],
       see=['Olympus Stylus Epic (mju-II) is the big one', 'Yashica T4/T5, Contax T2, Konica Big Mini', 'Premium lens branding: Zeiss, Hexanon']),
  dict(t='TI-84 Plus CE graphing calculator', cat='Electronics', sub='Calculators', brand='Texas Instruments', model='TI-84 Plus CE',
       eb='ti-84 plus ce graphing calculator -case -cover -charger', ship='small', test=L, fake=L, ret=L, frag=L, know=BEG, req=RECOMMENDED,
       cost=(3, 15), loc='Thrift store, Bins, Yard sale',
       chk=['Powers on and holds a charge', 'All keys respond', 'Screen has no lines', 'Not engraved with a school name'],
       see=['Color screen = CE (worth the most)', 'TI-83/84 Plus black-and-white are lower', 'Back-to-school season (Aug–Sep) is peak']),
  dict(t='Brother QL label printer', cat='Electronics', sub='Label printers', brand='Brother', model='QL series',
       eb='brother ql label printer -labels -roll -rolls', ship='medium', test=M, fake=L, ret=L, frag=L, know=BEG, req=RECOMMENDED,
       cost=(5, 20), loc='Thrift store, Estate sale, Marketplace',
       chk=['Power adapter or cord present (often missing)', 'DK roll compartment cover intact', 'USB cable', 'Cutter not jammed'],
       see=['QL-500/570/700/800 model numbers', 'DK roll compartment on top', 'Resellers buy these for shipping labels']),
  dict(t='Dymo LabelWriter 450', cat='Electronics', sub='Label printers', brand='Dymo', model='LabelWriter 450',
       eb='dymo labelwriter 450 -labels -roll -rolls', ship='medium', test=M, fake=L, ret=L, frag=L, know=BEG, req=RECOMMENDED,
       cost=(5, 20), loc='Thrift store, Estate sale, Marketplace',
       chk=['Power supply present', 'Feeds a label', 'Lid hinge not cracked'], see=['LabelWriter 450 / 450 Turbo / 4XL', 'Office surplus lots']),
  dict(t='Vintage stereo receiver', cat='Electronics', sub='Receivers', model='Pioneer SX / Marantz / Sansui / Technics',
       eb='vintage stereo receiver (pioneer,marantz,sansui,technics) -parts -knob -knobs -faceplate', ship='bulky', test=H, fake=L, ret=H, frag=M, know=SPEC, req=MUST,
       cost=(15, 60), loc='Estate sale, Yard sale, Marketplace, Thrift store',
       chk=['Powers on and dial lamps light', 'Plug in headphones and test both channels', 'Knobs all present and not scratchy', 'No burnt smell', 'Wood case condition'],
       see=['Silver faceplate 1970s models', 'Pioneer SX-series, Marantz 22xx, Sansui G/AU', 'Heavy for its size = good transformer', 'Local pickup often nets more than shipping']),
  dict(t='Sony Walkman cassette player', cat='Electronics', sub='Media players', brand='Sony', model='WM series',
       eb='sony walkman cassette player -parts -belt -case', ship='small', test=H, fake=L, ret=H, frag=M, know=MODK, req=MUST,
       cost=(3, 20), loc='Thrift store, Bins, Estate sale, Yard sale',
       chk=['Plays a tape at steady speed (no warble)', 'Battery compartment free of corrosion', 'Buttons latch', 'Belt not melted'],
       see=['WM-F / WM-D6C Professional are premium', 'Chrome and yellow Sports models', 'Untested units sell for parts prices only']),
  dict(t='Sony Discman portable CD player', cat='Electronics', sub='Media players', brand='Sony', model='D-EJ / D-NE series',
       eb='sony discman portable cd player -parts -case', ship='small', test=H, fake=L, ret=M, frag=M, know=BEG, req=MUST,
       cost=(3, 15), loc='Thrift store, Bins, Yard sale',
       chk=['Spins and reads a CD', 'Lid latch works', 'Battery compartment clean', 'Headphone jack has sound in both sides'],
       see=['ESP / G-Protection anti-skip branding', 'Y2K aesthetic demand']),
  dict(t='Bose QuietComfort headphones', cat='Electronics', sub='Headphones', brand='Bose', model='QC35 / QC45',
       eb='bose quietcomfort headphones -case -cushions -pads -cable', ship='small', test=M, fake=M, ret=M, frag=L, know=MODK, req=RECOMMENDED,
       cost=(8, 30), loc='Thrift store, Marketplace, Yard sale',
       chk=['Pairs and plays sound in both cups', 'Noise cancelling engages', 'Ear pads not flaking (cheap to replace)', 'Serial number label inside the cup'],
       see=['QC35 II, QC45, 700', 'Fakes have wrong fonts and no serial label']),
  dict(t='Sony WH-1000XM4 headphones', cat='Electronics', sub='Headphones', brand='Sony', model='WH-1000XM4',
       eb='sony wh-1000xm4 headphones -case -pads -cable', ship='small', test=M, fake=M, ret=M, frag=L, know=MODK, req=RECOMMENDED,
       cost=(10, 40), loc='Marketplace, Thrift store',
       chk=['Pairs and touch controls work', 'Noise cancelling engages', 'Headband not cracked at the hinge'], see=['XM3/XM4/XM5 model on the inner band']),
  dict(t='Logitech MX Master mouse', cat='Electronics', sub='Computers', brand='Logitech', model='MX Master 2S / 3',
       eb='logitech mx master wireless mouse -receiver -charger', ship='small', test=L, fake=L, ret=L, frag=L, know=BEG, req=RECOMMENDED,
       cost=(3, 12), loc='Thrift store, Bins, Estate sale',
       chk=['Charges and pairs', 'Scroll wheel clicks into free-spin', 'Rubber grip not sticky'], see=['MX Master 3 / 3S / 2S']),
  dict(t='Apple iPad', cat='Electronics', sub='Tablets', brand='Apple',
       eb='apple ipad wifi -case -keyboard -cover -parts -broken -locked', ship='small', test=H, fake=L, ret=H, frag=H, know=MODK, req=MUST,
       cost=(10, 60), loc='Thrift store, Marketplace, Yard sale',
       chk=['NOT activation-locked (reset to "Hello" screen — no Apple ID prompt)', 'Screen not cracked; touch works everywhere', 'Battery holds charge', 'Model number on the back (Axxxx) for generation'],
       see=['A-number on the back identifies the generation', 'iCloud-locked iPads are parts-only', 'Newer generations support current iPadOS and sell far higher']),
  dict(t='Garmin eTrex handheld GPS', cat='Electronics', sub='GPS devices', brand='Garmin', model='eTrex',
       eb='garmin etrex handheld gps -mount -case -cable', ship='small', test=M, fake=L, ret=L, frag=L, know=BEG, req=RECOMMENDED,
       cost=(4, 20), loc='Thrift store, Estate sale, Yard sale',
       chk=['Powers on with AA batteries', 'Acquires satellites outdoors', 'Screen not faded'], see=['eTrex 10/20/30, GPSMAP series']),
  dict(t='Logitech Harmony remote', cat='Electronics', sub='Remote controls', brand='Logitech', model='Harmony Elite / 650 / 700',
       eb='logitech harmony remote -hub -battery -charger', ship='small', test=M, fake=L, ret=L, frag=L, know=BEG, req=RECOMMENDED,
       cost=(2, 10), loc='Thrift store, Bins, Estate sale',
       chk=['Screen lights up', 'Battery door present', 'Charging cradle for Elite/Companion models'], see=['Discontinued line — demand from people replacing broken ones']),
  dict(t='Apple iPod classic', cat='Electronics', sub='Media players', brand='Apple', model='iPod classic / video',
       eb='apple ipod classic -case -battery -parts -broken', ship='small', test=H, fake=L, ret=M, frag=M, know=MODK, req=MUST,
       cost=(5, 30), loc='Thrift store, Bins, Estate sale, Yard sale',
       chk=['Powers on without the sad-iPod icon', 'Click wheel responds', 'Hard drive does not click', 'Capacity engraved on the back'],
       see=['160GB and 5th-gen video models sell best', 'Engraved backs are fine', 'Modded flash-storage iPods sell high']),
  dict(t='Bose SoundLink speaker', cat='Electronics', sub='Speakers', brand='Bose', model='SoundLink Mini / Color / Flex',
       eb='bose soundlink bluetooth speaker -case -charger -cover', ship='small', test=M, fake=M, ret=L, frag=L, know=BEG, req=RECOMMENDED,
       cost=(5, 25), loc='Thrift store, Yard sale, Marketplace',
       chk=['Charges and pairs', 'No rattle at high volume', 'Charging port not loose'], see=['SoundLink Mini II with charging cradle', 'Flex and Revolve']),

  # ------------------------------------------------------------------ Gaming
  dict(t='Nintendo Switch console', cat='Gaming', sub='Consoles', brand='Nintendo', model='HAC-001 / OLED',
       eb='nintendo switch console -broken -parts -repair -lite', ship='medium', test=H, fake=L, ret=H, frag=M, know=MODK, req=MUST,
       cost=(40, 120), loc='Marketplace, Yard sale, Thrift store',
       chk=['Boots to the home screen', 'Not banned from online (try the eShop)', 'Joy-Cons connect and do not drift', 'Game card slot reads', 'Dock and charger included'],
       see=['Red box = extended-battery model, OLED has a larger screen', 'Serial starting XAW1 may be the older model']),
  dict(t='Nintendo 3DS XL', cat='Gaming', sub='Handhelds', brand='Nintendo', model='3DS XL / New 3DS XL',
       eb='nintendo 3ds xl console -case -charger -game -games -broken', ship='small', test=M, fake=L, ret=M, frag=M, know=BEG, req=RECOMMENDED,
       cost=(20, 70), loc='Thrift store, Yard sale, Marketplace',
       chk=['Both screens light with no scratches on the top screen', 'Hinge is not cracked', 'Circle pad and buttons respond', 'Charger included'],
       see=['"New" 3DS XL has a C-stick nub', 'Limited editions (Pokemon, Zelda) sell higher']),
  dict(t='Game Boy Advance SP', cat='Gaming', sub='Handhelds', brand='Nintendo', model='AGS-001 / AGS-101',
       eb='game boy advance sp console -shell -replacement -broken', ship='small', test=M, fake=M, ret=M, frag=M, know=MODK, req=RECOMMENDED,
       cost=(15, 50), loc='Thrift store, Yard sale, Flea market',
       chk=['AGS-101 on the back = brighter backlit screen (worth more)', 'Hinge tight', 'Charges', 'Screen scratches'],
       see=['Model number sticker on the back', 'Aftermarket reshells lower the price']),
  dict(t='PlayStation 2 slim console', cat='Gaming', sub='Retro gaming', brand='Sony', model='SCPH-7xxxx / 9xxxx',
       eb='playstation 2 slim console -broken -parts -repair', ship='medium', test=H, fake=L, ret=M, frag=L, know=BEG, req=MUST,
       cost=(15, 40), loc='Thrift store, Yard sale, Marketplace',
       chk=['Reads a disc (ask to test)', 'Lid closes and latches', 'Power brick included for slims', 'Controller ports work'],
       see=['Slim models SCPH-7xxxx/9xxxx', 'Fat models with network adapters sell to collectors']),
  dict(t='Xbox wireless controller', cat='Gaming', sub='Controllers', brand='Microsoft', model='Series X|S / One',
       eb='xbox wireless controller -charger -skin -broken -parts', ship='small', test=M, fake=L, ret=M, frag=L, know=BEG, req=RECOMMENDED,
       cost=(5, 20), loc='Thrift store, Bins, Yard sale',
       chk=['Sticks do not drift', 'Triggers and bumpers click', 'Battery cover present'], see=['Special edition colors sell higher']),
  dict(t='Nintendo 64 controller', cat='Gaming', sub='Controllers', brand='Nintendo', model='NUS-005',
       eb='nintendo 64 controller oem -joystick -replacement', ship='small', test=M, fake=M, ret=M, frag=L, know=MODK, req=RECOMMENDED,
       cost=(5, 20), loc='Thrift store, Yard sale, Flea market',
       chk=['Joystick is tight (loose sticks lower value)', 'NUS-005 printed on the back', 'Nintendo logo on the front'], see=['Colored OEM variants (Atomic Purple, Jungle Green) sell higher', 'Knockoffs lack the NUS-005 label']),
  dict(t='Pokemon Nintendo DS game', cat='Gaming', sub='Games', brand='Nintendo', model='HeartGold / SoulSilver / Platinum',
       eb='pokemon nintendo ds game -repro -reproduction -lot', ship='small', test=M, fake=H, ret=H, frag=L, know=SPEC, req=AUTH,
       cost=(3, 30), loc='Thrift store, Yard sale, Flea market',
       chk=['Back label has a code printed in the lower corner', 'Cartridge back has the correct "TWL" code and Nintendo stamp', 'HeartGold/SoulSilver: real carts are dark translucent/infrared back'],
       see=['HeartGold, SoulSilver, Platinum, Black 2, White 2 are high value', 'Bootlegs have glossy labels and cheap plastic']),
  dict(t='Sony PSP console', cat='Gaming', sub='Handhelds', brand='Sony', model='PSP-1000/2000/3000',
       eb='sony psp console -case -battery -charger -game -broken -parts', ship='small', test=M, fake=L, ret=M, frag=M, know=BEG, req=RECOMMENDED,
       cost=(15, 45), loc='Thrift store, Yard sale, Marketplace',
       chk=['Powers on and holds a charge (swollen batteries are common)', 'UMD drive reads', 'Screen scratches'], see=['PSP-3000 has the best screen', 'Limited edition colors']),
  dict(t='GameCube controller', cat='Gaming', sub='Controllers', brand='Nintendo', model='DOL-003',
       eb='nintendo gamecube controller oem -adapter -replacement', ship='small', test=M, fake=M, ret=M, frag=L, know=MODK, req=RECOMMENDED,
       cost=(5, 20), loc='Thrift store, Yard sale, Flea market',
       chk=['DOL-003 on the back', 'Sticks snap back to center', 'Cord not frayed'], see=['Smash players pay a premium for tight sticks']),

  # ------------------------------------------------------------------ Music gear
  dict(t='Boss guitar pedal', cat='Music Gear', sub='Pedals', brand='Boss', model='DS-1 / BD-2 / DD-3 / RC-30',
       eb='boss guitar effects pedal -power -supply -board', ship='small', test=M, fake=L, ret=M, frag=L, know=MODK, req=RECOMMENDED,
       cost=(10, 35), loc='Thrift store, Yard sale, Marketplace, Flea market',
       chk=['Battery door present', 'Jacks not crackly', 'LED lights when active'], see=['Made in Japan versions are worth more', 'Looper (RC) and delay (DD) sell highest']),
  dict(t='Electro-Harmonix guitar pedal', cat='Music Gear', sub='Pedals', brand='Electro-Harmonix', model='Big Muff / Holy Grail',
       eb='electro-harmonix guitar pedal -power -supply', ship='small', test=M, fake=L, ret=M, frag=L, know=MODK, req=RECOMMENDED,
       cost=(10, 35), loc='Thrift store, Marketplace, Flea market',
       chk=['Footswitch clicks and engages', 'Power jack works'], see=['Big Muff variants', 'Vintage NYC-made units are collectible']),
  dict(t='Focusrite Scarlett audio interface', cat='Music Gear', sub='Audio interfaces', brand='Focusrite', model='Scarlett 2i2 / Solo',
       eb='focusrite scarlett audio interface -cable', ship='small', test=M, fake=L, ret=M, frag=L, know=BEG, req=RECOMMENDED,
       cost=(10, 40), loc='Thrift store, Marketplace, Yard sale',
       chk=['USB connection recognized by a phone/laptop', 'Gain knobs not scratchy', 'Headphone output has sound'], see=['2i2 3rd/4th Gen sell best', 'Generation printed on the bottom']),
  dict(t='Shure SM58 microphone', cat='Music Gear', sub='Microphones', brand='Shure', model='SM58',
       eb='shure sm58 microphone -clip -grille -cable -case', ship='small', test=L, fake=H, ret=M, frag=L, know=MODK, req=AUTH,
       cost=(8, 30), loc='Thrift store, Marketplace, Estate sale',
       chk=['Grille unscrews and the cartridge is branded Shure', 'Serial number on the XLR end', '"Made in Mexico" or USA'],
       see=['Fakes are extremely common — look for a light, hollow feel and "Made in China"', 'Beta 58A is the upgraded model']),
  dict(t='Akai MPK Mini MIDI controller', cat='Music Gear', sub='Keyboards', brand='Akai', model='MPK Mini',
       eb='akai mpk mini midi keyboard controller -case', ship='medium', test=M, fake=L, ret=L, frag=L, know=BEG, req=RECOMMENDED,
       cost=(10, 35), loc='Thrift store, Marketplace, Yard sale',
       chk=['Every key and pad triggers', 'Knobs send data', 'USB port not loose'], see=['MK3 has the OLED screen', 'Play and special edition colors']),
  dict(t='Mackie mixer', cat='Music Gear', sub='Recording equipment', brand='Mackie', model='ProFX / 402VLZ',
       eb='mackie mixer -bag -cover -knob', ship='medium', test=H, fake=L, ret=M, frag=L, know=MODK, req=MUST,
       cost=(10, 40), loc='Estate sale, Marketplace, Thrift store',
       chk=['Power supply included', 'Every channel passes signal', 'Faders and pots not scratchy'], see=['VLZ and ProFX lines', 'Church and school surplus']),
  dict(t='Numark DJ controller', cat='Music Gear', sub='DJ equipment', brand='Numark', model='Party Mix / Mixtrack',
       eb='numark dj controller -case -bag', ship='large', test=M, fake=L, ret=M, frag=L, know=BEG, req=RECOMMENDED,
       cost=(10, 40), loc='Thrift store, Marketplace, Yard sale',
       chk=['Jog wheels respond', 'Crossfader smooth', 'USB recognized'], see=['Mixtrack Pro 3 / Platinum FX', 'Party Mix is entry-level and low value']),
  dict(t='Squier Stratocaster electric guitar', cat='Music Gear', sub='Guitars', brand='Fender / Squier', model='Stratocaster',
       eb='squier stratocaster electric guitar -case -neck -body -pickguard -parts', ship='large', test=M, fake=M, ret=M, frag=M, know=MODK, req=RECOMMENDED,
       cost=(30, 90), loc='Marketplace, Yard sale, Estate sale, Thrift store',
       chk=['Neck is straight (sight down it)', 'Every pickup works through an amp', 'Frets not deeply grooved', 'Tuners all present', 'Serial number on the headstock or neck plate'],
       see=['Classic Vibe and Japanese-made (JV/SQ serial) Squiers sell highest', 'Fender-logo copies with the wrong headstock shape are fakes']),

  # ------------------------------------------------------------------ Tools
  dict(t='Milwaukee M18 battery', cat='Tools', sub='Batteries', brand='Milwaukee', model='M18 REDLITHIUM',
       eb='milwaukee m18 battery -charger -adapter -tool -replacement', ship='small', test=M, fake=H, ret=M, frag=L, know=MODK, req=AUTH,
       cost=(10, 40), loc='Yard sale, Estate sale, Marketplace, Flea market',
       chk=['Fuel gauge lights when pressed', 'Heavy for its size (fakes are light)', 'Label print is crisp and the date code is present', 'Latch not cracked'],
       see=['High Output 6.0/8.0/12.0 sell highest', 'Knockoffs say "M18" but have wrong fonts and no date code']),
  dict(t='DeWalt 20V MAX drill driver', cat='Tools', sub='Power tools', brand='DeWalt', model='DCD771 / DCD791',
       eb='dewalt 20v max drill driver -battery -charger -kit', ship='medium', test=M, fake=L, ret=L, frag=L, know=BEG, req=RECOMMENDED,
       cost=(10, 35), loc='Yard sale, Estate sale, Marketplace, Thrift store',
       chk=['Runs smoothly in both directions (bring a battery)', 'Chuck grips a bit', 'Clutch settings click'], see=['Brushless (XR) models sell higher']),
  dict(t='Makita 18V LXT impact driver', cat='Tools', sub='Power tools', brand='Makita', model='XDT',
       eb='makita 18v lxt impact driver -battery -charger', ship='medium', test=M, fake=L, ret=L, frag=L, know=BEG, req=RECOMMENDED,
       cost=(10, 35), loc='Yard sale, Estate sale, Marketplace',
       chk=['Impacts under load', 'LED works', 'Bit holder retains a bit'], see=['XDT13/XDT16 brushless models']),
  dict(t='Milwaukee M12 FUEL tool', cat='Tools', sub='Power tools', brand='Milwaukee', model='M12 FUEL',
       eb='milwaukee m12 fuel tool only', ship='medium', test=M, fake=L, ret=L, frag=L, know=MODK, req=RECOMMENDED,
       cost=(15, 45), loc='Yard sale, Estate sale, Marketplace',
       chk=['Runs with an M12 battery', 'No burning smell'], see=['FUEL badge = brushless', 'Stubby impact wrenches and ratchets sell well']),
  dict(t='DeWalt 20V battery charger', cat='Tools', sub='Chargers', brand='DeWalt', model='DCB112 / DCB115',
       eb='dewalt 20v max charger dcb115', ship='small', test=M, fake=M, ret=L, frag=L, know=BEG, req=RECOMMENDED,
       cost=(3, 12), loc='Yard sale, Estate sale, Thrift store', chk=['Lights when plugged in', 'Cord intact'], see=['DCB115 fast charger sells higher']),
  dict(t='Stanley Bailey hand plane', cat='Tools', sub='Vintage hand tools', brand='Stanley', model='No. 4 / No. 5',
       eb='stanley bailey no 4 hand plane', ship='medium', test=L, fake=L, ret=L, frag=M, know=SPEC, req=UNTESTED,
       cost=(5, 25), loc='Estate sale, Yard sale, Flea market',
       chk=['Casting has no cracks (look at the cheeks and mouth)', 'Lever cap and blade present', 'Tote handle not broken'],
       see=['"Sweetheart" logo on the blade = 1920s-30s', 'Type 11-16 frog adjusters', 'Rust is fine; cracks are not']),
  dict(t='Bosch laser measure', cat='Tools', sub='Specialty tools', brand='Bosch', model='GLM series',
       eb='bosch glm laser measure -case', ship='small', test=M, fake=L, ret=L, frag=L, know=BEG, req=RECOMMENDED,
       cost=(5, 20), loc='Estate sale, Yard sale, Thrift store', chk=['Powers on and reads a distance', 'Screen legible'], see=['GLM 50C / 165 series']),

  # ------------------------------------------------------------------ Home
  dict(t='Dyson V8 cordless vacuum', cat='Home', sub='Vacuums', brand='Dyson', model='V8',
       eb='dyson v8 cordless vacuum -parts -filter -replacement', ship='large', test=H, fake=L, ret=M, frag=L, know=MODK, req=MUST,
       cost=(15, 50), loc='Thrift store, Marketplace, Yard sale',
       chk=['Runs without pulsing (pulsing = blocked filter or bad battery)', 'Battery holds a charge', 'Bin latch intact', 'Charger included'],
       see=['V-model printed on the handle', 'Parts-out value (motor, battery, heads) if it does not run']),
  dict(t='Nespresso Vertuo coffee machine', cat='Home', sub='Coffee equipment', brand='Nespresso', model='Vertuo',
       eb='nespresso vertuo coffee machine -pods -capsules', ship='large', test=M, fake=L, ret=M, frag=M, know=BEG, req=RECOMMENDED,
       cost=(8, 30), loc='Thrift store, Yard sale, Marketplace',
       chk=['Powers on and head locks', 'Water tank not cracked', 'Descaling light not permanently on'], see=['Vertuo Next / Plus / Pop']),
  dict(t='KitchenAid stand mixer attachment', cat='Home', sub='Kitchenware', brand='KitchenAid', model='Pasta roller / meat grinder',
       eb='kitchenaid stand mixer attachment -bowl', ship='medium', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED,
       cost=(3, 15), loc='Thrift store, Estate sale, Yard sale',
       chk=['All parts present (grinder plates, pasta cutters)', 'No rust on metal parts'], see=['Pasta roller sets and slicer/shredders sell best']),
  dict(t='Le Creuset Dutch oven', cat='Home', sub='Kitchenware', brand='Le Creuset',
       eb='le creuset dutch oven -knob -replacement', ship='bulky', test=L, fake=L, ret=L, frag=M, know=BEG, req=UNTESTED,
       cost=(5, 40), loc='Estate sale, Thrift store, Yard sale',
       chk=['Enamel not chipped inside', 'Lid included and fits', 'Size number cast on the bottom'], see=['"Le Creuset France" cast on the base', 'Heavy — local pickup nets more']),
  dict(t='Vintage Pyrex bowl', cat='Home', sub='Kitchenware', brand='Pyrex',
       eb='vintage pyrex mixing bowl -lid', ship='medium', test=L, fake=L, ret=M, frag=H, know=MODK, req=UNTESTED,
       cost=(2, 15), loc='Estate sale, Thrift store, Yard sale, Flea market',
       chk=['No chips on the rim', 'Pattern not dishwasher-faded (dull, chalky)', 'Stamp on the bottom'], see=['Butterprint, Gooseberry, Pink Daisy patterns', 'Primary-color nesting bowls']),
  dict(t='Vitamix blender base', cat='Home', sub='Small appliances', brand='Vitamix', model='5200 / E310 / 750',
       eb='vitamix blender base -parts -replacement', ship='large', test=M, fake=L, ret=M, frag=L, know=BEG, req=RECOMMENDED,
       cost=(15, 60), loc='Thrift store, Estate sale, Marketplace',
       chk=['Motor runs at all speeds without burning smell', 'Drive socket not stripped', 'Container included'], see=['5200 and Professional 750 sell well']),
  dict(t='Mid century modern table lamp', cat='Home', sub='Lamps', eb='mid century modern table lamp -harp -finial',
       ship='bulky', test=M, fake=L, ret=M, frag=H, know=SPEC, req=RECOMMENDED,
       cost=(5, 40), loc='Estate sale, Thrift store, Flea market',
       chk=['Lights up; cord not brittle', 'Ceramic base not cracked', 'Shade may be replaceable'], see=['Ceramic drip glaze bases, brass and teak', 'Designer marks on the base']),
  dict(t='Corningware Blue Cornflower', cat='Home', sub='Kitchenware', brand='Corning', eb='corningware blue cornflower casserole',
       ship='medium', test=L, fake=L, ret=M, frag=H, know=BEG, req=UNTESTED,
       cost=(2, 10), loc='Estate sale, Thrift store, Yard sale', chk=['No chips or cracks', 'Lids match the size'], see=['Blue cornflower pattern, P-series numbers']),

  # ------------------------------------------------------------------ Collectibles
  dict(t='LEGO bulk lot', cat='Collectibles', sub='Toys', brand='LEGO', eb='lego bulk lot pounds -duplo',
       ship='large', test=L, fake=M, ret=L, frag=L, know=MODK, req=UNTESTED,
       cost=(5, 30), loc='Thrift store, Yard sale, Estate sale, Marketplace',
       chk=['Weigh or estimate pounds', 'LEGO stamped on the studs (knockoffs are blank)', 'Minifigures and named sets add value', 'Not mixed with Mega Bloks'],
       see=['Resale is priced per pound — sold range reflects lot size', 'Star Wars, Technic and castle parts lift the value']),
  dict(t='Vintage Star Wars action figure', cat='Collectibles', sub='Figurines', brand='Kenner',
       eb='vintage star wars action figure kenner loose -reproduction -repro', ship='small', test=L, fake=H, ret=M, frag=L, know=SPEC, req=AUTH,
       cost=(1, 20), loc='Estate sale, Yard sale, Flea market',
       chk=['Copyright stamp on the leg (©LFL, Hong Kong/Taiwan)', 'Accessories are often reproductions', 'Limbs tight, paint not worn'],
       see=['1977–1985 Kenner figures', 'Original weapons are worth more than the figure sometimes']),
  dict(t='Pokemon cards lot', cat='Collectibles', sub='Trading cards', brand='Pokemon',
       eb='pokemon cards lot -digital -code -online -proxy', ship='small', test=L, fake=H, ret=M, frag=L, know=SPEC, req=AUTH,
       cost=(2, 30), loc='Yard sale, Thrift store, Estate sale, Flea market',
       chk=['Check card stock — fakes are glossy and flimsy', 'Look for holos, first edition stamps and older sets', 'Rip test is never an option — use the light test'],
       see=['Base Set, Jungle, Fossil (1999–2000)', 'Shadowless and 1st Edition stamps', 'Bulk common lots sell by count']),
  dict(t='Squishmallows plush', cat='Collectibles', sub='Plush', brand='Squishmallows',
       eb='squishmallow plush -keychain -lot', ship='medium', test=L, fake=M, ret=L, frag=L, know=MODK, req=UNTESTED,
       cost=(2, 10), loc='Thrift store, Bins, Yard sale',
       chk=['Tag attached (tag-less sells for far less)', 'No stains or pilling'], see=['Rare named characters sell high; most are common']),
  dict(t='Hot Wheels Redline', cat='Collectibles', sub='Toys', brand='Hot Wheels',
       eb='hot wheels redline vintage -reproduction -restored', ship='small', test=L, fake=M, ret=M, frag=L, know=SPEC, req=AUTH,
       cost=(1, 20), loc='Estate sale, Yard sale, Flea market',
       chk=['Red stripe on the tires', 'Base says Mattel 1967–1977 with country (USA/Hong Kong)', 'Paint condition drives value'], see=['Spectraflame paint', 'Restored cars sell for much less']),
  dict(t='Vintage advertising tin sign', cat='Collectibles', sub='Advertising', eb='vintage advertising tin sign original -reproduction -repro',
       ship='large', test=L, fake=H, ret=M, frag=M, know=SPEC, req=AUTH,
       cost=(10, 60), loc='Estate sale, Flea market, Yard sale',
       chk=['Genuine age wear (not uniform fake rust)', 'Maker marks along the edge', 'Grommet holes show old wear'], see=['Oil, soda and seed company signs', 'Reproductions are everywhere — be skeptical']),
  dict(t='Vintage concert tour program', cat='Collectibles', sub='Memorabilia', eb='vintage concert tour program book',
       ship='small', test=L, fake=M, ret=L, frag=L, know=MODK, req=UNTESTED,
       cost=(1, 10), loc='Estate sale, Thrift store, Flea market', chk=['Cover not torn', 'No water damage'], see=['70s/80s rock tour books']),

  # ------------------------------------------------------------------ Sporting goods
  dict(t='TaylorMade driver', cat='Sporting Goods', sub='Golf', brand='TaylorMade',
       eb='taylormade driver -headcover -adapter', ship='large', test=L, fake=M, ret=M, frag=L, know=MODK, req=AUTH,
       cost=(10, 40), loc='Thrift store, Yard sale, Estate sale',
       chk=['Crown not caved or cracked', 'Loft and shaft flex printed', 'Serial number on the hosel'], see=['M-series, SIM, Stealth', 'Fakes have poor paint fill and no serial']),
  dict(t='Scotty Cameron putter', cat='Sporting Goods', sub='Golf', brand='Titleist / Scotty Cameron',
       eb='scotty cameron putter -headcover', ship='large', test=L, fake=H, ret=M, frag=L, know=SPEC, req=AUTH,
       cost=(15, 80), loc='Estate sale, Thrift store, Yard sale',
       chk=['Weight ports and sole stamps crisp', 'Grip is the correct Scotty grip', 'Serial on the hosel/shaft'], see=['Newport and Squareback models', 'Very commonly faked — authenticate before paying up']),
  dict(t='Titleist Pro V1 used golf balls', cat='Sporting Goods', sub='Golf', brand='Titleist',
       eb='titleist pro v1 used golf balls lot', ship='medium', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED,
       cost=(1, 8), loc='Thrift store, Yard sale, Estate sale', chk=['Count them', 'No cuts or water-logged discoloring'], see=['Sold by the dozen']),
  dict(t='Osprey hiking backpack', cat='Sporting Goods', sub='Outdoor gear', brand='Osprey',
       eb='osprey hiking backpack -kids -cover', ship='medium', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED,
       cost=(8, 30), loc='Thrift store, Estate sale, Marketplace',
       chk=['Zippers and buckles all work', 'Hip belt padding intact', 'No sticky PU coating inside'], see=['Atmos, Exos, Aether multi-day packs']),
  dict(t='Coleman vintage camp stove', cat='Sporting Goods', sub='Camping', brand='Coleman',
       eb='vintage coleman camp stove -parts', ship='large', test=M, fake=L, ret=L, frag=L, know=MODK, req=RECOMMENDED,
       cost=(5, 25), loc='Estate sale, Yard sale, Flea market',
       chk=['Generator and tank present', 'Date stamp on the tank', 'Minimal rust on the burners'], see=['Green 413/425 two-burners', 'Date code stamped on the tank bottom']),
  dict(t='Bowflex SelectTech dumbbells', cat='Sporting Goods', sub='Fitness', brand='Bowflex', model='552 / 1090',
       eb='bowflex selecttech 552 dumbbells pair -plate -plates -knob -dial -tray -stand -replacement -parts -handle -single', ship='local', test=L, fake=L, ret=M, frag=L, know=BEG, req=RECOMMENDED,
       cost=(40, 120), loc='Marketplace, Yard sale',
       chk=['Dials turn and every weight plate locks', 'Both dumbbells and trays present'], plat='Heavy — Facebook Marketplace local pickup is usually best',
       see=['552 (5–52.5 lb) and 1090 models']),
  dict(t='Garmin Forerunner watch', cat='Sporting Goods', sub='Fitness', brand='Garmin', model='Forerunner',
       eb='garmin forerunner gps watch -band -charger -strap', ship='small', test=M, fake=L, ret=M, frag=L, know=BEG, req=RECOMMENDED,
       cost=(10, 40), loc='Thrift store, Marketplace, Yard sale',
       chk=['Charges with the clip cable (ask for it)', 'Buttons all respond', 'Screen not scratched deeply', 'Not linked to someone\'s account (factory reset)'],
       see=['Forerunner 245/255/945/955 sell highest']),

  # ------------------------------------------------------------------ Auto / specialty
  dict(t='WeatherTech floor mats', cat='Auto / Specialty', sub='OEM accessories', brand='WeatherTech',
       eb='weathertech floorliner floor mats', ship='large', test=L, fake=L, ret=M, frag=L, know=MODK, req=UNTESTED,
       cost=(5, 30), loc='Yard sale, Marketplace, Estate sale',
       chk=['Vehicle fit number molded on the back', 'Not cracked or warped'], see=['Fit is vehicle-specific — note the model years']),
  dict(t='Autel OBD2 scanner', cat='Auto / Specialty', sub='Replacement components', brand='Autel',
       eb='autel obd2 scanner diagnostic', ship='small', test=M, fake=L, ret=M, frag=L, know=MODK, req=RECOMMENDED,
       cost=(5, 30), loc='Yard sale, Estate sale, Marketplace',
       chk=['Powers on when plugged in', 'Screen and buttons work'], see=['MaxiCOM and MaxiSys lines sell well']),
  dict(t='Pioneer car stereo head unit', cat='Auto / Specialty', sub='Auto parts', brand='Pioneer',
       eb='pioneer car stereo receiver head unit -parts', ship='medium', test=H, fake=L, ret=M, frag=L, know=MODK, req=MUST,
       cost=(5, 30), loc='Yard sale, Marketplace, Flea market',
       chk=['Faceplate present', 'Wiring harness included', 'Anti-theft code not locked'], see=['Double-DIN CarPlay units sell highest']),

  # ------------------------------------------------------------------ Media
  dict(t='Classic rock vinyl LP', cat='Media', sub='Vinyl', eb='classic rock vinyl lp record',
       ship='medium', test=L, fake=L, ret=M, frag=M, know=SPEC, req=UNTESTED,
       cost=(1, 10), loc='Estate sale, Thrift store, Yard sale, Flea market',
       chk=['Vinyl not warped (sight along the edge)', 'Scratches you can feel skip', 'Inner sleeve and inserts present', 'Check the matrix number in the run-out groove'],
       see=['Original pressings beat reissues', 'Led Zeppelin, Pink Floyd, Fleetwood Mac, Beatles', 'Promo stamps and misprints']),
  dict(t='Criterion Collection Blu-ray', cat='Media', sub='DVDs/Blu-rays', brand='Criterion',
       eb='criterion collection blu-ray -dvd', ship='small', test=L, fake=L, ret=L, frag=L, know=BEG, req=UNTESTED,
       cost=(1, 8), loc='Thrift store, Estate sale, Yard sale',
       chk=['Disc present and not scratched', 'Booklet inside'], see=['Spine number on the case', 'Out-of-print titles sell highest']),
  dict(t='Complete series DVD box set', cat='Media', sub='Box sets', eb='complete series dvd box set -blu-ray',
       ship='medium', test=L, fake=M, ret=M, frag=L, know=BEG, req=UNTESTED,
       cost=(2, 10), loc='Thrift store, Estate sale, Yard sale',
       chk=['Every disc present', 'Region 1 (bootlegs are often region-free and flimsy)'], see=['Out-of-print TV series', 'Bootleg sets have misspellings and thin packaging']),
  dict(t='Stephen King first edition hardcover', cat='Media', sub='Rare editions', brand='Stephen King',
       eb='stephen king first edition hardcover -bce -bookclub', ship='medium', test=L, fake=L, ret=M, frag=L, know=SPEC, req=AUTH,
       cost=(1, 10), loc='Estate sale, Thrift store, Yard sale, Flea market',
       chk=['"First Edition" stated on the copyright page', 'Dust jacket has a price (book club editions do not)', 'Not a Book Club Edition (blind stamp on the back board)'],
       see=['Carrie, Salem\'s Lot, The Shining early editions', 'Book club copies are worth very little']),
  dict(t='Vintage cookbook', cat='Media', sub='Books', eb='vintage cookbook -reprint',
       ship='medium', test=L, fake=L, ret=L, frag=L, know=MODK, req=UNTESTED,
       cost=(1, 6), loc='Estate sale, Thrift store, Yard sale',
       chk=['Binding intact', 'Pages not stained heavily'], see=['Betty Crocker picture cookbooks, spiral-bound church and advertising cookbooks']),
]


def slug(term):
    return re.sub(r'^-+|-+$', '', re.sub(r'[^a-z0-9]+', '-', term.lower()))


def rows():
    out = []
    for r in ROWS:
        cost = r.get('cost') or (None, None)
        out.append({
            'opportunityId': slug(r['t']),
            'searchTerm': r['t'],
            'ebayQuery': r.get('eb', ''),
            'poshmarkQuery': r.get('pm', ''),
            'brand': r.get('brand', ''),
            'model': r.get('model', ''),
            'category': r['cat'],
            'subcategory': r.get('sub', ''),
            'keywords': r.get('kw', ''),
            'shippingClass': r.get('ship', ''),
            'testingRisk': r.get('test', ''),
            'counterfeitRisk': r.get('fake', ''),
            'shippingDifficulty': SHIP_DIFFICULTY.get(r.get('ship', ''), ''),
            'fragility': r.get('frag', ''),
            'returnRisk': r.get('ret', ''),
            'knowledgeLevel': r.get('know', ''),
            'conditionRequirement': r.get('req', ''),
            'typicalCostLow': cost[0] if cost[0] is not None else '',
            'typicalCostHigh': cost[1] if cost[1] is not None else '',
            'sourcingLocations': r.get('loc', ''),
            'inspectionNotes': '\n'.join(r.get('chk', [])),
            'recognitionNotes': '\n'.join(r.get('see', [])),
            'platformNotes': r.get('plat', ''),
            'active': 'Y',
        })
    return out


if __name__ == '__main__':
    data = rows()
    ids = [d['opportunityId'] for d in data]
    dupes = {i for i in ids if ids.count(i) > 1}
    if dupes:
        sys.exit(f'duplicate opportunity ids: {dupes}')
    json.dump(data, sys.stdout, indent=1)
